Update ids.xml
Newest gradle update has caused this:
error: <item> inner element must either be a resource reference or empty.
I have tracked it down to this single <item>.